2018-06-05 12:26:34,157 ERROR: Exception on /search [GET] [in c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\main\routes.py", line 144, in search
    current_app.config['POSTS_PER_PAGE'])
  File "C:\Users\Woong Wen Tat\flask-microblog\app\models.py", line 91, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\search.py", line 21, in query_index
    if not current_app.elasticsearch:
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'elasticsearch'
2018-06-05 12:26:46,513 ERROR: Exception on /search [GET] [in c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\main\routes.py", line 144, in search
    current_app.config['POSTS_PER_PAGE'])
  File "C:\Users\Woong Wen Tat\flask-microblog\app\models.py", line 91, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\search.py", line 21, in query_index
    if not current_app.elasticsearch:
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'elasticsearch'
2018-06-05 12:29:22,779 ERROR: Exception on /index [POST] [in c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\main\routes.py", line 35, in index
    db.session.commit()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\sqlalchemy\orm\scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\sqlalchemy\orm\session.py", line 906, in commit
    self.transaction.commit()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\sqlalchemy\orm\session.py", line 468, in commit
    self.session.dispatch.after_commit(self.session)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\sqlalchemy\event\attr.py", line 218, in __call__
    fn(*args, **kw)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\models.py", line 112, in after_commit
    add_to_index(obj.__tablename__, obj)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\search.py", line 5, in add_to_index
    if not current_app.elasticsearch:
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'elasticsearch'
2018-06-05 12:29:38,266 ERROR: Exception on /index [POST] [in c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\main\routes.py", line 35, in index
    db.session.commit()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\sqlalchemy\orm\scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\sqlalchemy\orm\session.py", line 906, in commit
    self.transaction.commit()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\sqlalchemy\orm\session.py", line 468, in commit
    self.session.dispatch.after_commit(self.session)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\sqlalchemy\event\attr.py", line 218, in __call__
    fn(*args, **kw)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\models.py", line 112, in after_commit
    add_to_index(obj.__tablename__, obj)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\search.py", line 5, in add_to_index
    if not current_app.elasticsearch:
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'elasticsearch'
2018-06-05 12:30:05,336 ERROR: Exception on /index [POST] [in c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\main\routes.py", line 35, in index
    db.session.commit()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\sqlalchemy\orm\scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\sqlalchemy\orm\session.py", line 906, in commit
    self.transaction.commit()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\sqlalchemy\orm\session.py", line 468, in commit
    self.session.dispatch.after_commit(self.session)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\sqlalchemy\event\attr.py", line 218, in __call__
    fn(*args, **kw)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\models.py", line 112, in after_commit
    add_to_index(obj.__tablename__, obj)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\search.py", line 5, in add_to_index
    if not current_app.elasticsearch:
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'elasticsearch'
